FROM ubuntu:26.04

RUN useradd -U builder --shell /bin/sh --home-dir /home/builder --create-home \
    && apt-get update && apt-get install -y \
    build-essential \
    bash \
    tar \
    gzip \
    cpio \
    rpm2cpio \
    patch \
    perl \
    sed \
    findutils \
    rsync \
    coreutils \
    bc \
    bison \
    flex \
    libelf-dev \
    libssl-dev \
    kmod \
    dwarves \
    autoconf \
    automake \
    libtool \
    gawk \
    debhelper \
    fakeroot \
    dpkg-dev \
    dkms \
    libblkid-dev \
    uuid-dev \
    libudev-dev \
    zlib1g-dev \
    libaio-dev \
    libattr1-dev \
    libtirpc-dev \
    python3 \
    python3-dev \
    python3-setuptools \
    python3-cffi \
    libcurl4-openssl-dev \
    dh-python \
    libpam0g-dev \
    lsb-release \
    python3-all-dev \
    python3-sphinx \
    dkms \
    dh-dkms \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER builder
